trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- name: service_connection
  value: platform-images

container:
  image: iacdev000acr000.azurecr.io/platform-images:latest
  endpoint: platform-images

steps:
- checkout: self
  persistCredentials: true
- script: |
    export GIT_CREDENTIALS=$(System.AccessToken)
    make GIT_TOKEN=$(System.AccessToken) configure
    make release 
    make clean
    